- name: install docker
  hosts: all
  roles:
          - install-docker
  tags: install

- name: initialise docker swarm 
  hosts: alma
  roles:
          - swarm-init 

- name: Add wrker nodes
  hosts: all
  roles:
          - add-worker 
- name: swarm service
  hosts: alma
  roles:
          - swarm-service
  tags: deploy 
