---
# tasks file for swarm-init
- name: Get info on Docker Swarm
  docker_swarm_info:
  ignore_errors: yes
  register: swarm_info

- name: Init a new swarm with default parameters
  docker_swarm:
          state: present
          advertise_addr: "{{ hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address'] }}"
  when:  swarm_info != 0 
  run_once: true


- name: Get info on Docker Swarm and filtered list of registered nodes
  docker_swarm_info:
  register: result

