---
# tasks file for swarm-service

- name: Start service 
  docker_swarm_service:
    name: myservice
    image: nginx:latest
    replicas: 4
    publish:
            - published_port: 8080
              target_port: 80
              protocol: tcp
              mode: host

